//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilevus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ilevus.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para a página inicial.
        /// </summary>
        public static string ActionBackToMainPage {
            get {
                return ResourceManager.GetString("ActionBackToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail e/ou senha inválido(s)..
        /// </summary>
        public static string AuthInvalidUserCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidUserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexta-feira.
        /// </summary>
        public static string DayFriday {
            get {
                return ResourceManager.GetString("DayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sex.
        /// </summary>
        public static string DayFridayAbbr {
            get {
                return ResourceManager.GetString("DayFridayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda-feira.
        /// </summary>
        public static string DayMonday {
            get {
                return ResourceManager.GetString("DayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seg.
        /// </summary>
        public static string DayMondayAbbr {
            get {
                return ResourceManager.GetString("DayMondayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        public static string DaySaturday {
            get {
                return ResourceManager.GetString("DaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sáb.
        /// </summary>
        public static string DaySaturdayAbbr {
            get {
                return ResourceManager.GetString("DaySaturdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        public static string DaySunday {
            get {
                return ResourceManager.GetString("DaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dom.
        /// </summary>
        public static string DaySundayAbbr {
            get {
                return ResourceManager.GetString("DaySundayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinta-feira.
        /// </summary>
        public static string DayThursday {
            get {
                return ResourceManager.GetString("DayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qui.
        /// </summary>
        public static string DayThursdayAbbr {
            get {
                return ResourceManager.GetString("DayThursdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terça-feira.
        /// </summary>
        public static string DayTuesday {
            get {
                return ResourceManager.GetString("DayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ter.
        /// </summary>
        public static string DayTuesdayAbbr {
            get {
                return ResourceManager.GetString("DayTuesdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarta-feira.
        /// </summary>
        public static string DayWednesday {
            get {
                return ResourceManager.GetString("DayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qua.
        /// </summary>
        public static string DayWednesdayAbbr {
            get {
                return ResourceManager.GetString("DayWednesdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações da conta.
        /// </summary>
        public static string LabelAccountConfig {
            get {
                return ResourceManager.GetString("LabelAccountConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anúncio.
        /// </summary>
        public static string LabelAd {
            get {
                return ResourceManager.GetString("LabelAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string LabelBirthdate {
            get {
                return ResourceManager.GetString("LabelBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string LabelComplement {
            get {
                return ResourceManager.GetString("LabelComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar e-mail.
        /// </summary>
        public static string LabelConfirmEmail {
            get {
                return ResourceManager.GetString("LabelConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LabelCounty {
            get {
                return ResourceManager.GetString("LabelCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string LabelDistrict {
            get {
                return ResourceManager.GetString("LabelDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        public static string LabelEditProfile {
            get {
                return ResourceManager.GetString("LabelEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade.
        /// </summary>
        public static string LabelExpertise {
            get {
                return ResourceManager.GetString("LabelExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro nome.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string LabelGenre {
            get {
                return ResourceManager.GetString("LabelGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        public static string LabelLocalization {
            get {
                return ResourceManager.GetString("LabelLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atende online.
        /// </summary>
        public static string LabelMeetsOnline {
            get {
                return ResourceManager.GetString("LabelMeetsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens.
        /// </summary>
        public static string LabelMessages {
            get {
                return ResourceManager.GetString("LabelMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme sua senha.
        /// </summary>
        public static string LabelPasswordConfirm {
            get {
                return ResourceManager.GetString("LabelPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string LabelPasswordNew {
            get {
                return ResourceManager.GetString("LabelPasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Telefone.
        /// </summary>
        public static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil profissional.
        /// </summary>
        public static string LabelProfessionalProfile {
            get {
                return ResourceManager.GetString("LabelProfessionalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string LabelSex {
            get {
                return ResourceManager.GetString("LabelSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartilhar.
        /// </summary>
        public static string LabelShare {
            get {
                return ResourceManager.GetString("LabelShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string LabelSignIn {
            get {
                return ResourceManager.GetString("LabelSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string LabelSignUp {
            get {
                return ResourceManager.GetString("LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanecer conectado.
        /// </summary>
        public static string LabelStayConnected {
            get {
                return ResourceManager.GetString("LabelStayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string LabelSurname {
            get {
                return ResourceManager.GetString("LabelSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar Endereço.
        /// </summary>
        public static string LabelUpdateAddress {
            get {
                return ResourceManager.GetString("LabelUpdateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string LabelZipcode {
            get {
                return ResourceManager.GetString("LabelZipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string MonthApril {
            get {
                return ResourceManager.GetString("MonthApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abr.
        /// </summary>
        public static string MonthAprilAbbr {
            get {
                return ResourceManager.GetString("MonthAprilAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string MonthAugust {
            get {
                return ResourceManager.GetString("MonthAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string MonthAugustAbbr {
            get {
                return ResourceManager.GetString("MonthAugustAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        public static string MonthDecember {
            get {
                return ResourceManager.GetString("MonthDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dez.
        /// </summary>
        public static string MonthDecemberAbbr {
            get {
                return ResourceManager.GetString("MonthDecemberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        public static string MonthFebruary {
            get {
                return ResourceManager.GetString("MonthFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fev.
        /// </summary>
        public static string MonthFebruaryAbbr {
            get {
                return ResourceManager.GetString("MonthFebruaryAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        public static string MonthJanuary {
            get {
                return ResourceManager.GetString("MonthJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jan.
        /// </summary>
        public static string MonthJanuaryAbbr {
            get {
                return ResourceManager.GetString("MonthJanuaryAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        public static string MonthJuly {
            get {
                return ResourceManager.GetString("MonthJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jul.
        /// </summary>
        public static string MonthJulyAbbr {
            get {
                return ResourceManager.GetString("MonthJulyAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        public static string MonthJune {
            get {
                return ResourceManager.GetString("MonthJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jun.
        /// </summary>
        public static string MonthJuneAbbr {
            get {
                return ResourceManager.GetString("MonthJuneAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        public static string MonthMarch {
            get {
                return ResourceManager.GetString("MonthMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mar.
        /// </summary>
        public static string MonthMarchAbbr {
            get {
                return ResourceManager.GetString("MonthMarchAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        public static string MonthMay {
            get {
                return ResourceManager.GetString("MonthMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mai.
        /// </summary>
        public static string MonthMayAbbr {
            get {
                return ResourceManager.GetString("MonthMayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        public static string MonthNovember {
            get {
                return ResourceManager.GetString("MonthNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nov.
        /// </summary>
        public static string MonthNovemberAbbr {
            get {
                return ResourceManager.GetString("MonthNovemberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        public static string MonthOctober {
            get {
                return ResourceManager.GetString("MonthOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        public static string MonthOctoberAbbr {
            get {
                return ResourceManager.GetString("MonthOctoberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        public static string MonthSeptember {
            get {
                return ResourceManager.GetString("MonthSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        public static string MonthSeptemberAbbr {
            get {
                return ResourceManager.GetString("MonthSeptemberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta criada com sucesso..
        /// </summary>
        public static string TextAccountCreated {
            get {
                return ResourceManager.GetString("TextAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os direitos reservados..
        /// </summary>
        public static string TextAllRightsReserved {
            get {
                return ResourceManager.GetString("TextAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um e-mail de confirmação foi enviado para o endereço cadastrado..
        /// </summary>
        public static string TextEmailConfirmationSent {
            get {
                return ResourceManager.GetString("TextEmailConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} avaliações.
        /// </summary>
        public static string TextEvaluations {
            get {
                return ResourceManager.GetString("TextEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você pode ter digitado algum endereço errado ou a página foi movida deste lugar..
        /// </summary>
        public static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, não encontramos a página que você está procurando....
        /// </summary>
        public static string TextNotFoundOops {
            get {
                return ResourceManager.GetString("TextNotFoundOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já possui uma conta?.
        /// </summary>
        public static string TextQHaveAccount {
            get {
                return ResourceManager.GetString("TextQHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar sua senha.
        /// </summary>
        public static string TextRecoverPassword {
            get {
                return ResourceManager.GetString("TextRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nós iremos enviar instruções de como recuperar sua senha para o email em que você se cadastrou. Confira sua caixa de entrada após confirmar a solicitação..
        /// </summary>
        public static string TextRecoverPasswordDescription {
            get {
                return ResourceManager.GetString("TextRecoverPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de recuperação de senha enviado com sucesso..
        /// </summary>
        public static string TextRecoverPasswordEmailSent {
            get {
                return ResourceManager.GetString("TextRecoverPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resultado(s) encontrado(s) para &quot;{1}&quot;..
        /// </summary>
        public static string TextSearchNumberOfResults {
            get {
                return ResourceManager.GetString("TextSearchNumberOfResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquise por nome, especialidade ou localização....
        /// </summary>
        public static string TextSearchPlaceholder {
            get {
                return ResourceManager.GetString("TextSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça seu login.
        /// </summary>
        public static string TextSignIn {
            get {
                return ResourceManager.GetString("TextSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar uma conta.
        /// </summary>
        public static string TextSignUp {
            get {
                return ResourceManager.GetString("TextSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao clicar em &quot;Criar minha conta&quot;, você está de acordo com nossa Política de Privacidade e Termos de Uso..
        /// </summary>
        public static string TextSignUpAgreement {
            get {
                return ResourceManager.GetString("TextSignUpAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça seu cadastro grátis em segundos, não precisa de cartão de crédito..
        /// </summary>
        public static string TextSignUpDescription {
            get {
                return ResourceManager.GetString("TextSignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie a sua conta agora.
        /// </summary>
        public static string TextSignUpTitle {
            get {
                return ResourceManager.GetString("TextSignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforme sua carreira..
        /// </summary>
        public static string TextSlogan {
            get {
                return ResourceManager.GetString("TextSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontre os melhores profissionais de consultoria e coaching para auxiliá-lo em sua carreira..
        /// </summary>
        public static string TextSloganDescription {
            get {
                return ResourceManager.GetString("TextSloganDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu e-mail..
        /// </summary>
        public static string TextTypeYourEmail {
            get {
                return ResourceManager.GetString("TextTypeYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a sua senha..
        /// </summary>
        public static string TextTypeYourPassword {
            get {
                return ResourceManager.GetString("TextTypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro inesperado ocorreu. Por favor, tente novamente mais tarde. Caso o erro persista, entre em contato com o suporte..
        /// </summary>
        public static string TextUnexpectedError {
            get {
                return ResourceManager.GetString("TextUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, um erro inesperado ocorreu....
        /// </summary>
        public static string TextUnexpectedErrorOops {
            get {
                return ResourceManager.GetString("TextUnexpectedErrorOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas digitadas não são iguais..
        /// </summary>
        public static string ValidationPasswordsDontMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; é obrigatório..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; precisa ter no mínimo {2} caracteres..
        /// </summary>
        public static string ValidationStringLengthMin {
            get {
                return ResourceManager.GetString("ValidationStringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é obrigatório..
        /// </summary>
        public static string ValidationSurnameRequired {
            get {
                return ResourceManager.GetString("ValidationSurnameRequired", resourceCulture);
            }
        }
    }
}
