//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ilevus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ilevus.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar idioma.
        /// </summary>
        public static string ActionAddLanguage {
            get {
                return ResourceManager.GetString("ActionAddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar nova experiência profissional.
        /// </summary>
        public static string ActionAddNewCareerExperience {
            get {
                return ResourceManager.GetString("ActionAddNewCareerExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar nova formação.
        /// </summary>
        public static string ActionAddNewEducation {
            get {
                return ResourceManager.GetString("ActionAddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar novo serviço.
        /// </summary>
        public static string ActionAddNewOfferedService {
            get {
                return ResourceManager.GetString("ActionAddNewOfferedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para o login.
        /// </summary>
        public static string ActionBackToLogin {
            get {
                return ResourceManager.GetString("ActionBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para a página inicial.
        /// </summary>
        public static string ActionBackToMainPage {
            get {
                return ResourceManager.GetString("ActionBackToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar e-mail.
        /// </summary>
        public static string ActionChangeEmail {
            get {
                return ResourceManager.GetString("ActionChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar idioma.
        /// </summary>
        public static string ActionChangeLanguage {
            get {
                return ResourceManager.GetString("ActionChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar senha.
        /// </summary>
        public static string ActionChangePassword {
            get {
                return ResourceManager.GetString("ActionChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string ActionConfirm {
            get {
                return ResourceManager.GetString("ActionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar minha conta.
        /// </summary>
        public static string ActionCreateMyAccount {
            get {
                return ResourceManager.GetString("ActionCreateMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string ActionRemove {
            get {
                return ResourceManager.GetString("ActionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover idioma.
        /// </summary>
        public static string ActionRemoveLanguage {
            get {
                return ResourceManager.GetString("ActionRemoveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover foto.
        /// </summary>
        public static string ActionRemovePicture {
            get {
                return ResourceManager.GetString("ActionRemovePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar reunião.
        /// </summary>
        public static string ActionRequestMeeting {
            get {
                return ResourceManager.GetString("ActionRequestMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar telefone.
        /// </summary>
        public static string ActionRequestPhone {
            get {
                return ResourceManager.GetString("ActionRequestPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar experiência profissional.
        /// </summary>
        public static string ActionSaveCareerExperience {
            get {
                return ResourceManager.GetString("ActionSaveCareerExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar formação.
        /// </summary>
        public static string ActionSaveEducation {
            get {
                return ResourceManager.GetString("ActionSaveEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar serviço.
        /// </summary>
        public static string ActionSaveOfferedService {
            get {
                return ResourceManager.GetString("ActionSaveOfferedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar mensagem.
        /// </summary>
        public static string ActionSendMessage {
            get {
                return ResourceManager.GetString("ActionSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar uma foto.
        /// </summary>
        public static string ActionSendPicture {
            get {
                return ResourceManager.GetString("ActionSendPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail e/ou senha inválido(s)..
        /// </summary>
        public static string AuthInvalidUserCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidUserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexta-feira.
        /// </summary>
        public static string DayFriday {
            get {
                return ResourceManager.GetString("DayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sex.
        /// </summary>
        public static string DayFridayAbbr {
            get {
                return ResourceManager.GetString("DayFridayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda-feira.
        /// </summary>
        public static string DayMonday {
            get {
                return ResourceManager.GetString("DayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seg.
        /// </summary>
        public static string DayMondayAbbr {
            get {
                return ResourceManager.GetString("DayMondayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        public static string DaySaturday {
            get {
                return ResourceManager.GetString("DaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sáb.
        /// </summary>
        public static string DaySaturdayAbbr {
            get {
                return ResourceManager.GetString("DaySaturdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        public static string DaySunday {
            get {
                return ResourceManager.GetString("DaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dom.
        /// </summary>
        public static string DaySundayAbbr {
            get {
                return ResourceManager.GetString("DaySundayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinta-feira.
        /// </summary>
        public static string DayThursday {
            get {
                return ResourceManager.GetString("DayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qui.
        /// </summary>
        public static string DayThursdayAbbr {
            get {
                return ResourceManager.GetString("DayThursdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terça-feira.
        /// </summary>
        public static string DayTuesday {
            get {
                return ResourceManager.GetString("DayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ter.
        /// </summary>
        public static string DayTuesdayAbbr {
            get {
                return ResourceManager.GetString("DayTuesdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarta-feira.
        /// </summary>
        public static string DayWednesday {
            get {
                return ResourceManager.GetString("DayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qua.
        /// </summary>
        public static string DayWednesdayAbbr {
            get {
                return ResourceManager.GetString("DayWednesdayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacharel.
        /// </summary>
        public static string EducationTypeBachelor {
            get {
                return ResourceManager.GetString("EducationTypeBachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mestrado.
        /// </summary>
        public static string EducationTypeMasters {
            get {
                return ResourceManager.GetString("EducationTypeMasters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        public static string EducationTypeOther {
            get {
                return ResourceManager.GetString("EducationTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doutorado.
        /// </summary>
        public static string EducationTypePhD {
            get {
                return ResourceManager.GetString("EducationTypePhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialização.
        /// </summary>
        public static string EducationTypeSpecialization {
            get {
                return ResourceManager.GetString("EducationTypeSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnico.
        /// </summary>
        public static string EducationTypeTechnical {
            get {
                return ResourceManager.GetString("EducationTypeTechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Olá {0},&lt;/p&gt;&lt;p&gt;Por favor, confirme seu e-mail acessando o link:&lt;br /&gt;{1}&lt;/p&gt;--&lt;br /&gt;Equipe ilevus.
        /// </summary>
        public static string EmailConfirmEmailBody {
            get {
                return ResourceManager.GetString("EmailConfirmEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de e-mail.
        /// </summary>
        public static string EmailConfirmEmailSubject {
            get {
                return ResourceManager.GetString("EmailConfirmEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Olá {0},&lt;/p&gt;&lt;p&gt;Por favor, para redefinir sua senha, clique no link abaixo:&lt;br /&gt;{1}&lt;/p&gt;--&lt;br /&gt;Equipe ilevus.
        /// </summary>
        public static string EmailRecoverPasswordBody {
            get {
                return ResourceManager.GetString("EmailRecoverPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinição de senha.
        /// </summary>
        public static string EmailRecoverPasswordSubject {
            get {
                return ResourceManager.GetString("EmailRecoverPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre mim.
        /// </summary>
        public static string LabelAboutMe {
            get {
                return ResourceManager.GetString("LabelAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        public static string LabelAccount {
            get {
                return ResourceManager.GetString("LabelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações da conta.
        /// </summary>
        public static string LabelAccountConfig {
            get {
                return ResourceManager.GetString("LabelAccountConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de atuação.
        /// </summary>
        public static string LabelActuationArea {
            get {
                return ResourceManager.GetString("LabelActuationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anúncio.
        /// </summary>
        public static string LabelAd {
            get {
                return ResourceManager.GetString("LabelAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string LabelBack {
            get {
                return ResourceManager.GetString("LabelBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações básicas.
        /// </summary>
        public static string LabelBasicInfo {
            get {
                return ResourceManager.GetString("LabelBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações básicas.
        /// </summary>
        public static string LabelBasicInformation {
            get {
                return ResourceManager.GetString("LabelBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano de início.
        /// </summary>
        public static string LabelBeginYear {
            get {
                return ResourceManager.GetString("LabelBeginYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string LabelBirthdate {
            get {
                return ResourceManager.GetString("LabelBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa / Instituição.
        /// </summary>
        public static string LabelCareerInstitution {
            get {
                return ResourceManager.GetString("LabelCareerInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        public static string LabelCareerLocation {
            get {
                return ResourceManager.GetString("LabelCareerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo / Função.
        /// </summary>
        public static string LabelCareerRole {
            get {
                return ResourceManager.GetString("LabelCareerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar endereço de e-mail.
        /// </summary>
        public static string LabelChangeEmail {
            get {
                return ResourceManager.GetString("LabelChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar informações.
        /// </summary>
        public static string LabelChangeInformation {
            get {
                return ResourceManager.GetString("LabelChangeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar idioma de exibição.
        /// </summary>
        public static string LabelChangeLanguage {
            get {
                return ResourceManager.GetString("LabelChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altere a sua senha.
        /// </summary>
        public static string LabelChangePassword {
            get {
                return ResourceManager.GetString("LabelChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string LabelCompany {
            get {
                return ResourceManager.GetString("LabelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string LabelComplement {
            get {
                return ResourceManager.GetString("LabelComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar e-mail.
        /// </summary>
        public static string LabelConfirmEmail {
            get {
                return ResourceManager.GetString("LabelConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string LabelContinue {
            get {
                return ResourceManager.GetString("LabelContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LabelCounty {
            get {
                return ResourceManager.GetString("LabelCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de bordo.
        /// </summary>
        public static string LabelDashboard {
            get {
                return ResourceManager.GetString("LabelDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string LabelDistrict {
            get {
                return ResourceManager.GetString("LabelDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        public static string LabelEditProfile {
            get {
                return ResourceManager.GetString("LabelEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        public static string LabelEducationArea {
            get {
                return ResourceManager.GetString("LabelEducationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição de ensino.
        /// </summary>
        public static string LabelEducationInstitution {
            get {
                return ResourceManager.GetString("LabelEducationInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de formação.
        /// </summary>
        public static string LabelEducationType {
            get {
                return ResourceManager.GetString("LabelEducationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano de conclusão.
        /// </summary>
        public static string LabelEndYear {
            get {
                return ResourceManager.GetString("LabelEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiência.
        /// </summary>
        public static string LabelExperience {
            get {
                return ResourceManager.GetString("LabelExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade.
        /// </summary>
        public static string LabelExpertise {
            get {
                return ResourceManager.GetString("LabelExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        public static string LabelFinished {
            get {
                return ResourceManager.GetString("LabelFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro nome.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string LabelGenre {
            get {
                return ResourceManager.GetString("LabelGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frase de apresentação.
        /// </summary>
        public static string LabelHeadline {
            get {
                return ResourceManager.GetString("LabelHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caixa de entrada.
        /// </summary>
        public static string LabelInbox {
            get {
                return ResourceManager.GetString("LabelInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de atuação.
        /// </summary>
        public static string LabelIndustry {
            get {
                return ResourceManager.GetString("LabelIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma de exibição.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string LabelLanguages {
            get {
                return ResourceManager.GetString("LabelLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        public static string LabelLocalization {
            get {
                return ResourceManager.GetString("LabelLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer login com o Facebook.
        /// </summary>
        public static string LabelLoginWithFacebook {
            get {
                return ResourceManager.GetString("LabelLoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer login com o Linkedin.
        /// </summary>
        public static string LabelLoginWithLinkedin {
            get {
                return ResourceManager.GetString("LabelLoginWithLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atende online.
        /// </summary>
        public static string LabelMeetsOnline {
            get {
                return ResourceManager.GetString("LabelMeetsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens.
        /// </summary>
        public static string LabelMessages {
            get {
                return ResourceManager.GetString("LabelMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu endereço.
        /// </summary>
        public static string LabelMyAddress {
            get {
                return ResourceManager.GetString("LabelMyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string LabelNext {
            get {
                return ResourceManager.GetString("LabelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme sua senha.
        /// </summary>
        public static string LabelPasswordConfirm {
            get {
                return ResourceManager.GetString("LabelPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual.
        /// </summary>
        public static string LabelPasswordCurrent {
            get {
                return ResourceManager.GetString("LabelPasswordCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha.
        /// </summary>
        public static string LabelPasswordNew {
            get {
                return ResourceManager.GetString("LabelPasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        public static string LabelPeriod {
            get {
                return ResourceManager.GetString("LabelPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Telefone.
        /// </summary>
        public static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string LabelPrevious {
            get {
                return ResourceManager.GetString("LabelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil profissional.
        /// </summary>
        public static string LabelProfessionalProfile {
            get {
                return ResourceManager.GetString("LabelProfessionalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string LabelProfile {
            get {
                return ResourceManager.GetString("LabelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto do perfil.
        /// </summary>
        public static string LabelProfilePicture {
            get {
                return ResourceManager.GetString("LabelProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string LabelSelect {
            get {
                return ResourceManager.GetString("LabelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um idioma.
        /// </summary>
        public static string LabelSelectLanguage {
            get {
                return ResourceManager.GetString("LabelSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma foto de perfil.
        /// </summary>
        public static string LabelSelectPicture {
            get {
                return ResourceManager.GetString("LabelSelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço.
        /// </summary>
        public static string LabelService {
            get {
                return ResourceManager.GetString("LabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string LabelSex {
            get {
                return ResourceManager.GetString("LabelSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartilhar.
        /// </summary>
        public static string LabelShare {
            get {
                return ResourceManager.GetString("LabelShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string LabelSignIn {
            get {
                return ResourceManager.GetString("LabelSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string LabelSignUp {
            get {
                return ResourceManager.GetString("LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidades.
        /// </summary>
        public static string LabelSpecialties {
            get {
                return ResourceManager.GetString("LabelSpecialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciado em.
        /// </summary>
        public static string LabelStartedAt {
            get {
                return ResourceManager.GetString("LabelStartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanecer conectado.
        /// </summary>
        public static string LabelStayConnected {
            get {
                return ResourceManager.GetString("LabelStayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo.
        /// </summary>
        public static string LabelStep {
            get {
                return ResourceManager.GetString("LabelStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo.
        /// </summary>
        public static string LabelSummary {
            get {
                return ResourceManager.GetString("LabelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string LabelSurname {
            get {
                return ResourceManager.GetString("LabelSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to até.
        /// </summary>
        public static string LabelTo {
            get {
                return ResourceManager.GetString("LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar Endereço.
        /// </summary>
        public static string LabelUpdateAddress {
            get {
                return ResourceManager.GetString("LabelUpdateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string LabelWarning {
            get {
                return ResourceManager.GetString("LabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda trabalho aqui.
        /// </summary>
        public static string LabelWorkHere {
            get {
                return ResourceManager.GetString("LabelWorkHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string LabelZipcode {
            get {
                return ResourceManager.GetString("LabelZipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string LanguagePortuguese {
            get {
                return ResourceManager.GetString("LanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        public static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string MonthApril {
            get {
                return ResourceManager.GetString("MonthApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abr.
        /// </summary>
        public static string MonthAprilAbbr {
            get {
                return ResourceManager.GetString("MonthAprilAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string MonthAugust {
            get {
                return ResourceManager.GetString("MonthAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ago.
        /// </summary>
        public static string MonthAugustAbbr {
            get {
                return ResourceManager.GetString("MonthAugustAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        public static string MonthDecember {
            get {
                return ResourceManager.GetString("MonthDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dez.
        /// </summary>
        public static string MonthDecemberAbbr {
            get {
                return ResourceManager.GetString("MonthDecemberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        public static string MonthFebruary {
            get {
                return ResourceManager.GetString("MonthFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fev.
        /// </summary>
        public static string MonthFebruaryAbbr {
            get {
                return ResourceManager.GetString("MonthFebruaryAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        public static string MonthJanuary {
            get {
                return ResourceManager.GetString("MonthJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jan.
        /// </summary>
        public static string MonthJanuaryAbbr {
            get {
                return ResourceManager.GetString("MonthJanuaryAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        public static string MonthJuly {
            get {
                return ResourceManager.GetString("MonthJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jul.
        /// </summary>
        public static string MonthJulyAbbr {
            get {
                return ResourceManager.GetString("MonthJulyAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        public static string MonthJune {
            get {
                return ResourceManager.GetString("MonthJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jun.
        /// </summary>
        public static string MonthJuneAbbr {
            get {
                return ResourceManager.GetString("MonthJuneAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        public static string MonthMarch {
            get {
                return ResourceManager.GetString("MonthMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mar.
        /// </summary>
        public static string MonthMarchAbbr {
            get {
                return ResourceManager.GetString("MonthMarchAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        public static string MonthMay {
            get {
                return ResourceManager.GetString("MonthMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mai.
        /// </summary>
        public static string MonthMayAbbr {
            get {
                return ResourceManager.GetString("MonthMayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        public static string MonthNovember {
            get {
                return ResourceManager.GetString("MonthNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nov.
        /// </summary>
        public static string MonthNovemberAbbr {
            get {
                return ResourceManager.GetString("MonthNovemberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        public static string MonthOctober {
            get {
                return ResourceManager.GetString("MonthOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        public static string MonthOctoberAbbr {
            get {
                return ResourceManager.GetString("MonthOctoberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        public static string MonthSeptember {
            get {
                return ResourceManager.GetString("MonthSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        public static string MonthSeptemberAbbr {
            get {
                return ResourceManager.GetString("MonthSeptemberAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta criada com sucesso..
        /// </summary>
        public static string TextAccountCreated {
            get {
                return ResourceManager.GetString("TextAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira sua localização e seu endereço profissional..
        /// </summary>
        public static string TextAddressInfo {
            get {
                return ResourceManager.GetString("TextAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço atualizado com sucesso..
        /// </summary>
        public static string TextAddressUpdateSuccess {
            get {
                return ResourceManager.GetString("TextAddressUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os direitos reservados..
        /// </summary>
        public static string TextAllRightsReserved {
            get {
                return ResourceManager.GetString("TextAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira informações gerais sobre suas habilidades profissionais..
        /// </summary>
        public static string TextBasicProfessionalInfo {
            get {
                return ResourceManager.GetString("TextBasicProfessionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiência profissional.
        /// </summary>
        public static string TextCareer {
            get {
                return ResourceManager.GetString("TextCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carreira profissional e formação.
        /// </summary>
        public static string TextCareerEducation {
            get {
                return ResourceManager.GetString("TextCareerEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira as informações sobre suas experiências profissionais..
        /// </summary>
        public static string TextCareerProfessionalInfo {
            get {
                return ResourceManager.GetString("TextCareerProfessionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie seu perfil profissional na Ilevus..
        /// </summary>
        public static string TextCreateYourProfessionalProfile {
            get {
                return ResourceManager.GetString("TextCreateYourProfessionalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados salvos com sucesso..
        /// </summary>
        public static string TextDataSavedSuccessfully {
            get {
                return ResourceManager.GetString("TextDataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação acadêmica.
        /// </summary>
        public static string TextEducation {
            get {
                return ResourceManager.GetString("TextEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe sua formação acadêmica..
        /// </summary>
        public static string TextEducationProfessionalInfo {
            get {
                return ResourceManager.GetString("TextEducationProfessionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu e-mail já foi confirmado..
        /// </summary>
        public static string TextEmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("TextEmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um e-mail de confirmação foi enviado para o endereço cadastrado..
        /// </summary>
        public static string TextEmailConfirmationSent {
            get {
                return ResourceManager.GetString("TextEmailConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível confirmar o e-mail com este código, por favor solicite outro e-mail de confirmação..
        /// </summary>
        public static string TextEmailConfirmFailure {
            get {
                return ResourceManager.GetString("TextEmailConfirmFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu endereço de e-mail foi confirmado com sucesso..
        /// </summary>
        public static string TextEmailConfirmSuccess {
            get {
                return ResourceManager.GetString("TextEmailConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nós não compartilharemos o seu endereço de email privado com outros usuários..
        /// </summary>
        public static string TextEmailWillNotBeShared {
            get {
                return ResourceManager.GetString("TextEmailWillNotBeShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} avaliações.
        /// </summary>
        public static string TextEvaluations {
            get {
                return ResourceManager.GetString("TextEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você pode ter digitado algum endereço errado ou a página foi movida deste lugar..
        /// </summary>
        public static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, não encontramos a página que você está procurando....
        /// </summary>
        public static string TextNotFoundOops {
            get {
                return ResourceManager.GetString("TextNotFoundOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços oferecidos.
        /// </summary>
        public static string TextOfferedServices {
            get {
                return ResourceManager.GetString("TextOfferedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua senha foi alterada com sucesso..
        /// </summary>
        public static string TextPasswordSetSuccess {
            get {
                return ResourceManager.GetString("TextPasswordSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu número de telefone adiciona mais segurança à sua conta na Ilevus. Nós não iremos compartilhar essa informação com outros usuários..
        /// </summary>
        public static string TextPhoneHelp {
            get {
                return ResourceManager.GetString("TextPhoneHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua foto foi atualizada com sucesso..
        /// </summary>
        public static string TextPictureUpdateSuccess {
            get {
                return ResourceManager.GetString("TextPictureUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos claras e frontais do rosto são uma forma eficiente de ilustrar seu perfil..
        /// </summary>
        public static string TextProfilePictureDescription {
            get {
                return ResourceManager.GetString("TextProfilePictureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie um arquivo de imagem no formato JPG, GIF ou PNG de no máximo 1MB..
        /// </summary>
        public static string TextProfilePictureLimitations {
            get {
                return ResourceManager.GetString("TextProfilePictureLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do perfil atualizados com sucesso..
        /// </summary>
        public static string TextProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("TextProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já possui uma conta?.
        /// </summary>
        public static string TextQHaveAccount {
            get {
                return ResourceManager.GetString("TextQHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar sua senha.
        /// </summary>
        public static string TextRecoverPassword {
            get {
                return ResourceManager.GetString("TextRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nós iremos enviar instruções de como recuperar sua senha para o email em que você se cadastrou. Confira sua caixa de entrada após confirmar a solicitação..
        /// </summary>
        public static string TextRecoverPasswordDescription {
            get {
                return ResourceManager.GetString("TextRecoverPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de recuperação de senha enviado com sucesso..
        /// </summary>
        public static string TextRecoverPasswordEmailSent {
            get {
                return ResourceManager.GetString("TextRecoverPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrou sua senha? Faça seu login.
        /// </summary>
        public static string TextRecoverPasswordRemember {
            get {
                return ResourceManager.GetString("TextRecoverPasswordRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza de que deseja remover sua foto?.
        /// </summary>
        public static string TextRemovePictureConfirmation {
            get {
                return ResourceManager.GetString("TextRemovePictureConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resultado(s) encontrado(s) para &quot;{1}&quot;..
        /// </summary>
        public static string TextSearchNumberOfResults {
            get {
                return ResourceManager.GetString("TextSearchNumberOfResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquise por nome, especialidade ou localização....
        /// </summary>
        public static string TextSearchPlaceholder {
            get {
                return ResourceManager.GetString("TextSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique se os termos que pesquisou estão corretos ou se algum filtro está habilitado..
        /// </summary>
        public static string TextSearchVerifyTerms {
            get {
                return ResourceManager.GetString("TextSearchVerifyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar o meu perfil.
        /// </summary>
        public static string TextSeeMyProfile {
            get {
                return ResourceManager.GetString("TextSeeMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione seu país.
        /// </summary>
        public static string TextSelectYourCountry {
            get {
                return ResourceManager.GetString("TextSelectYourCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a foto que você deseja enviar:.
        /// </summary>
        public static string TextSendPicture {
            get {
                return ResourceManager.GetString("TextSendPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique e descreva os serviços que você oferece..
        /// </summary>
        public static string TextServicesProfessionalInfo {
            get {
                return ResourceManager.GetString("TextServicesProfessionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça seu login.
        /// </summary>
        public static string TextSignIn {
            get {
                return ResourceManager.GetString("TextSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar uma conta.
        /// </summary>
        public static string TextSignUp {
            get {
                return ResourceManager.GetString("TextSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao clicar em &quot;Criar minha conta&quot;, você está de acordo com nossa Política de Privacidade e Termos de Uso..
        /// </summary>
        public static string TextSignUpAgreement {
            get {
                return ResourceManager.GetString("TextSignUpAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça seu cadastro grátis em segundos, não precisa de cartão de crédito..
        /// </summary>
        public static string TextSignUpDescription {
            get {
                return ResourceManager.GetString("TextSignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie a sua conta agora.
        /// </summary>
        public static string TextSignUpTitle {
            get {
                return ResourceManager.GetString("TextSignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conduza seu sucesso.
        /// </summary>
        public static string TextSlogan {
            get {
                return ResourceManager.GetString("TextSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontre os melhores profissionais de coaching e consultoria profissional do mundo..
        /// </summary>
        public static string TextSloganDescription {
            get {
                return ResourceManager.GetString("TextSloganDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu e-mail..
        /// </summary>
        public static string TextTypeYourEmail {
            get {
                return ResourceManager.GetString("TextTypeYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a sua senha..
        /// </summary>
        public static string TextTypeYourPassword {
            get {
                return ResourceManager.GetString("TextTypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro inesperado ocorreu. Por favor, tente novamente mais tarde. Caso o erro persista, entre em contato com o suporte..
        /// </summary>
        public static string TextUnexpectedError {
            get {
                return ResourceManager.GetString("TextUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, um erro inesperado ocorreu....
        /// </summary>
        public static string TextUnexpectedErrorOops {
            get {
                return ResourceManager.GetString("TextUnexpectedErrorOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que não encontramos ninguém :(.
        /// </summary>
        public static string TextUserNotFound {
            get {
                return ResourceManager.GetString("TextUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o seu endereço.
        /// </summary>
        public static string TextWizardHeaderAddress {
            get {
                return ResourceManager.GetString("TextWizardHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comece por suas informações básicas.
        /// </summary>
        public static string TextWizardHeaderBasic {
            get {
                return ResourceManager.GetString("TextWizardHeaderBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este endereço de e-mail já está em uso..
        /// </summary>
        public static string ValidationEmailExists {
            get {
                return ResourceManager.GetString("ValidationEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string ValidationNameRequired {
            get {
                return ResourceManager.GetString("ValidationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua senha deve possuir pelo menos 1 número, 1 letra e 1 caractere especial..
        /// </summary>
        public static string ValidationPasswordFormat {
            get {
                return ResourceManager.GetString("ValidationPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa ter no mínimo {0} caracteres..
        /// </summary>
        public static string ValidationPasswordLength {
            get {
                return ResourceManager.GetString("ValidationPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas digitadas não são iguais..
        /// </summary>
        public static string ValidationPasswordsDontMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha digitada não é igual à confirmação da senha..
        /// </summary>
        public static string ValidationPasswordsDontMatchOnChange {
            get {
                return ResourceManager.GetString("ValidationPasswordsDontMatchOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone fornecido é inválido..
        /// </summary>
        public static string ValidationPhoneNumberInvalid {
            get {
                return ResourceManager.GetString("ValidationPhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto deve ter no máximo 1MB..
        /// </summary>
        public static string ValidationPictureMaxSize {
            get {
                return ResourceManager.GetString("ValidationPictureMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto deve ser um arquivo PNG, GIF ou JPG..
        /// </summary>
        public static string ValidationPictureType {
            get {
                return ResourceManager.GetString("ValidationPictureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; é obrigatório..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; precisa ter no mínimo {2} caracteres..
        /// </summary>
        public static string ValidationStringLengthMin {
            get {
                return ResourceManager.GetString("ValidationStringLengthMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é obrigatório..
        /// </summary>
        public static string ValidationSurnameRequired {
            get {
                return ResourceManager.GetString("ValidationSurnameRequired", resourceCulture);
            }
        }
    }
}
